name: Build2

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  ARTIFACT_DIR: ${{ github.workspace }}/artifacts

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30 

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        
    - name: Extract Version
      id: get_version
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: |
        $resourceFile = ".\OptiScaler\resource.h"
        if (-Not (Test-Path $resourceFile)) {
            Write-Error "File not found: $resourceFile"
            exit 1
        }
        
        function Get-Version-Component {
            param (
                [string]$pattern,
                [string]$replacement
            )
            try {
                $line = Get-Content $resourceFile | Select-String -Pattern $pattern | Select-Object -First 1
                return ($line.Line -replace $replacement).Trim()
            } catch {
                Write-Error "Pattern not found: $pattern"
                exit 1
            }
        }
        
        $majorVersion = Get-Version-Component 'VER_MAJOR_VERSION' '#define VER_MAJOR_VERSION\s+'
        $minorVersion = Get-Version-Component 'VER_MINOR_VERSION' '#define VER_MINOR_VERSION\s+'
        $hotfixVersion = Get-Version-Component 'VER_HOTFIX_VERSION' '#define VER_HOTFIX_VERSION\s+'
        $buildVersion = Get-Version-Component 'VER_BUILD_NUMBER' '#define VER_BUILD_NUMBER\s+'
        
        $version = "v$majorVersion.$minorVersion.$hotfixVersion-pre$buildVersion"
        $date = Get-Date -Format "yyyyMMdd"
        $outputFileName = "OptiScaler_${version}_${date}"
        
        Write-Output "Generated Filename: $outputFileName"
        
        "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "filename=$outputFileName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        
    - name: Debug Outputs
      run: |
        echo "Version: ${{ steps.get_version.outputs.version }}"
        echo "Filename: ${{ steps.get_version.outputs.filename }}"
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir -p ${{ env.ARTIFACT_DIR }}
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} `
               ${{env.SOLUTION_FILE_PATH}} `
               /p:OutDir=${{ env.ARTIFACT_DIR }} `
               /verbosity:minimal `
               /p:AdditionalIncludeDirectories="external/streamline"
      
    - name: Compress the artifact 
      run: |
        $zipName = "${{ steps.get_version.outputs.filename }}.7z"
        7z a ${{ github.workspace }}\$zipName ${{ env.ARTIFACT_DIR }}\*.*
        
    - name: Check for missing headers
      run: |
        find . -name '*.h' -o -name '*.hpp' | while read file; do
          grep -rnw './src' -e $(basename $file) || echo "Missing header: $file"
        done
      continue-on-error: true
      
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.get_version.outputs.filename }}
        path: ${{ github.workspace }}\${{ steps.get_version.outputs.filename }}.7z
        retention-days: 7
